import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import Main from "@/components/main/Main";

export const metadata = {
  title: "Blog-App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <Main>{children}</Main>
      </ThemeProvider>
    </html>
  );
}
